### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-node01#1]
- [x] spróbuj w ustawieniach terminala zrobić coś takiego: https://i.stack.imgur.com/DVjPA.png
- [x] rozbij `version` i `lang` na dwie osobne komendy

**Comment by patmaz** [comment]
1 - Ustawienia terminala zgadzają się.
2- https://github.com/patmaz/js-bootcamp-node01/commit/51768305105bfd25f51c4168e06497e793851493
