### ISSUE TITLE
Do poprawy 1.4

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-node01#2]
- [x] dobra praktyka nakazuje, aby przed `return` w funkcji był jeden enter
- [x] możesz zrobić:
``` js
var restSeconds = seconds % 60;
var minutes = (seconds - restSeconds) / 60;
```
dzięki temu pozbędziesz się `Math.floor()`
- [x] analogicznie w secondsToHours

**Comment by patmaz** [comment]
Uwagi wprowadzone: https://github.com/patmaz/js-bootcamp-node01/commit/8bb09ae062e1a1ee8e8ea1873c8d860bb9995379
Trzymałem się konwencji:
`var variable1 = 10,
        variable2 = 20;`
ponieważ podobno jest to bardziej wydajne od powtarzania `var` (???)
