### ISSUE TITLE
Do poprawy 1.7

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-node01#3]
bardzo fajnie, że stworzyłeś osobny moduł do obsługi I/O, ale jest kilka rzeczy, które można poprawić:
- [x] kod, który może potencjalnie wyrzucić błąd musi być opakowany w `try/catch`
- [x] raz korzystasz z metody `concat` innym razem dodajesz dwa stringi do siebie za pomocą '+'. Kod w 54. linijce można zapisać tak:
``` js
itemString += item
```
- [x] `console.log` w 59. linijce powinien być wewenątrz callbacka przekazanego do metody `wrtieFile` z 56. linijki
- [x] nie wszędzie sprawdzasz czy wystąpił błąd np. funkcja `readFile` z 37. linijki

**Comment by patmaz** [comment]
Zmiany i propozycja obsługi błędów: https://github.com/patmaz/js-bootcamp-node01/commit/d9e5f369b4dbefdf7a9da5525d3c3dd31ba2c422
